Umbenennung stille Treppe -> Calmdown
FU-Hagen-Discord/fernuni-bot pull request #106
Opened 2021-08-08 13:12 UTC by L-MzK

Um dem Vorwurf der Lehrerhaftigkeit keinen Platz zu geben.

2021-08-12 22:52 UTC, ffaadd requested changes
kleine Korrekturen, ansonsten wesentlich neutraler als die Stille Treppe. 
Werde sie vermissen ;-)

2021-08-12 22:52 UTC, ffaadd commented on cogs/calmdown.py
> +                await ctx.channel.send(f"{ctx.author.mention} hat {user.mention} von der **Auszeit** geholt.")
```suggestion
                await ctx.channel.send(f"{ctx.author.mention} hat {user.mention} aus der **Auszeit** geholt.")
```

2021-08-12 22:52 UTC, ffaadd commented on cogs/calmdown.py
> +                await utils.send_dm(user, f"Die Calmdown-Rolle wurde dir nun wieder entnommen.")
```suggestion
                await utils.send_dm(user, f"Die Calmdown-Rolle wurde nun wieder entfernt.")
```

2021-08-12 22:52 UTC, ffaadd commented on cogs/calmdown.py
> +            await ctx.channel.send(f"{ctx.author.mention} hat {user.mention} die **Calmdown-Rolle** vergeben.")
```suggestion
            await ctx.channel.send(f"{ctx.author.mention} hat an {user.mention} die **Calmdown-Rolle** vergeben.")
```

2021-08-12 22:52 UTC, ffaadd commented on cogs/calmdown.py
> +                await utils.send_dm(user, f"Dir wurde für {duration} Minuten die **Calmdown-Rolle** vergeben. Du kannst weiterhin alle Kanäle lesen, aber erst nach Ablauf der Zeit wieder an Gespräche
```suggestion
                await utils.send_dm(user, f"Dir wurde für {duration} Minuten die **Calmdown-Rolle** zugewiesen. Du kannst weiterhin alle Kanäle lesen, aber erst nach Ablauf der Zeit wieder an Gesprächen teilnehmen.")
```

2021-08-13 09:16 UTC, L-MzK commented on cogs/calmdown.py
> +                await utils.send_dm(user, f"Die Calmdown-Rolle wurde dir nun wieder entnommen.")
Danke!

2021-08-30 21:04 UTC, merged