Stellenangebote der Uni posten
FU-Hagen-Discord/fernuni-bot pull request #148
Opened 2022-02-12 12:46 UTC by samari-k

Alle Jobangebote (studentische Hilfskraft) einer Fakultät der Uni lassen sich mit `!jobs <fakultät>` auflisten. Standardmäßig (ohne Angabe der Fakultät werden die Angebote für MI ausgegeben. Das ließe sich für die anderen Server (wenn gewollt) einfach durch ändern von `STD_FAK="mi"` (Standard-Fakultät) zu rewi, wiwi, psy oder ksw abändern.

Zusätzlich überprüft Boty alle 24 Stunden die Jobangebote. Wenn neue in der eingestellten Standard-Fakultät auftauchen, informiert Boty darüber im stellenangebote-Channel.

closes #147 

![image](https://user-images.githubusercontent.com/74598487/153711782-7f7f13db-83d0-4137-981b-9e3bf0a0e830.png)
![image](https://user-images.githubusercontent.com/74598487/153711831-0bdaaa1d-30a3-43e3-84f9-171fdad338b6.png)

2022-02-24 23:40 UTC, dnns01 requested changes
@samari-k Schau dir die Kommentare mal an, ob du damit etwas anfangen kannst.

2022-02-24 23:40 UTC, dnns01 commented on cogs/job_offers.py
> +STD_FAK = "mi"
Am besten auch auslagern in `.env` Datei verschieben.

2022-02-24 23:40 UTC, dnns01 commented on cogs/job_offers.py
> +"""
Gar nicht schlecht. Jetzt im Nachhinein betrachtet, hätte das den anderen Dateien/Klassen auch nicht geschadet.

2022-02-24 23:40 UTC, dnns01 commented on cogs/job_offers.py
> +        self.load_joboffers()
Für das Laden sollten wir uns auch mal eine einheitliche Variante überlegen. Derzeit existieren Klassen, wie hier, bei denen die `load()` Methode in `self.joboffers` schreibt. Es existieren aber auch Klassen, bei denen die `load()` Methode das geladene JSON zurückgibt und im `__init__` die Zuweisung stattfindet.

2022-02-24 23:40 UTC, dnns01 commented on cogs/job_offers.py
> +        await interaction.response.send_message(embed=embed)
Evtl. besser das hier als Ephemeral zu senden, also nur an die Person, die das Command abgesetzt hat und nicht für alle sichtbar in den Channel schreiben.

2022-02-24 23:40 UTC, dnns01 commented on cogs/job_offers.py
> +            for offer in offers:
Das hier sollte auch durch ein 
```python
for offer in self.joboffers.get(faculty):
```
ersetzt werden können. Weil wenn bei `get` None raus kommt, dann Wird die Schleife einfach nicht durchlaufen. Müssen wir mal schauen.

2022-02-24 23:40 UTC, dnns01 commented on cogs/job_offers.py
> +            for offer in offers:
Außerdem kannst du per 
```python
for offer_id, offer_data in self.joboffers.get(faculty):
``` 
Nicht nur der Key (wie er derzeit in `offer` steckt) sondern auch direkt der Wert (hier ein weiteres Dictionary) Das heißt
```python
offer = offers[offer]
``` 
braucht es dann nicht mehr.

2022-02-24 23:40 UTC, dnns01 commented on cogs/job_offers.py
> +                    offer = fak[offer_id]
Eines der `if` kann auch hier durch die for Schleife ersetzt werden. Also beispielsweise
```python
if fak_old := old_joboffers.get(STD_FAK):
    for offer_id, offer_data in self.joboffers.get(STD_FAK).items():
```

2022-02-24 23:40 UTC, dnns01 commented on cogs/job_offers.py
> +                    offer = fak[offer_id]
Das gleiche auch hier. Ein offer können wir direkt über die for Schleife holen.

2022-02-25 05:46 UTC, samari-k commented on cogs/job_offers.py
> +        self.load_joboffers()
Ich finde es sinnvoll, die Zuweisung auch innerhalb der load() Funktion zu machen, das ist doch konsistent: Load lädt/schreibt die Daten aus der Datei in die Variable, save schreibt die Daten aus der Variable in die Datei. Was spräche für die andere Version?

2022-02-25 05:47 UTC, samari-k commented on cogs/job_offers.py
> +"""
lässt sich ja machen, ist schon übersichtlicher... Vielleicht als ein good first issue?

2022-02-25 05:47 UTC, samari-k commented on cogs/job_offers.py
> +STD_FAK = "mi"
done

2022-02-25 05:48 UTC, samari-k commented on cogs/job_offers.py
> +        await interaction.response.send_message(embed=embed)
Das war eigentlich auch mal meine Idee, keine Ahnung, warum ich es nicht gemacht hab. Erledigt.

2022-02-25 06:00 UTC, samari-k commented on cogs/job_offers.py
> +            for offer in offers:
ersteres umgesetzt, zweiteres klappt so nicht, da krieg ich `ValueError: too many values to unpack (expected 2)` zurück. schau ich mir später nochmal an

2022-02-25 07:20 UTC, samari-k commented on cogs/job_offers.py
> +            for offer in offers:
ha, es hat ein `.items()` gefehlt. klappt.

2022-02-25 07:35 UTC, samari-k commented
ich denke, ich habe alle Anmerkungen umgesetzt

2022-02-25 10:47 UTC, dnns01 commented on cogs/job_offers.py
> +        self.load_joboffers()
Ich finde das auch nicht sinnlos. Mir ist nur in erster Linie wieder eingefallen, dass wir hier über alle Klassen gesehen inkonsistent sind. Bzw. ich weiß, dass ich es mal so und mal so gemacht habe. Ich verstehe die Argumente für diese Version, hatte mir zwischenzeitilich nur gedacht, wenn die `load()` Funktion das Dictionary/Array zurückgibt, dann hat man in der `__init__` Deklaration von beispielsweise `self.joboffers` und Zuweisung des eigentlichen Wertes in einer Zeile.

2022-02-25 10:48 UTC, dnns01 commented on cogs/job_offers.py
> +"""
Ja, sollten wir mal diskutieren.

2022-02-25 10:49 UTC, dnns01 commented on cogs/job_offers.py
> +            for offer in offers:
Oh ja, das vergess ich gern :see_no_evil:

2022-03-03 22:45 UTC, dnns01 approved these changes

2022-03-03 23:13 UTC, dnns01 commented
Mit dem Embed kann es dazu führen, dass bei "zu vielen" neuen Stellenangeboten die maximale Größe gesprengt wird.

2022-03-03 23:22 UTC, dnns01 commented
Ist es erwünscht, dass `/jobs all` nichts zurückgibt, wenn `STD_FAK` nicht auf `all` eingestellt ist?

2022-03-03 23:23 UTC, dnns01 commented
```json
"8001s": {
      "title": "Studentische Hilfskraft mit Bachelor-Abschluss (Kennziffer 8001s)",
      "info": "Forschungsschwerpunkt D\u00c2\u00b2L\u00c2\u00b2, \u00e2\u20ac\u017eDigitalisierung, Diversit\u00e4t und Lebenslanges Lernen: Konsequenzen f\u00fcr die Hochschulbildung\u00e2\u20ac\u0153 sind f\u00fcr das Projekt IMPACT, einem Vorhaben zur Implementierung von Trusted Learning Analytics und KI",
      "deadline": "bis 06.03.2022 23:59",
      "link": "https://www.fernuni-hagen.de/uniintern/arbeitsthemen/karriere/stellen/hilfskraefte/index117162.shtml"
    },
```

Das in der JSON wird so im Embed angezeigt:
![image](https://user-images.githubusercontent.com/24375500/156669778-61efd66e-daaa-4005-a013-fac587baa557.png)

2022-03-04 13:05 UTC, samari-k commented
> Mit dem Embed kann es dazu führen, dass bei "zu vielen" neuen Stellenangeboten die maximale Größe gesprengt wird.
Das habe ich nicht bedacht. Sicher haben wir irgendwo bei Boty für diesen Fall schon ein gut funktionierendes Workaround was ich mir abschauen könnte? Hast du spontan ne Idee in welchem der cogs ich da fündig werde?

> Ist es erwünscht, dass /jobs all nichts zurückgibt, wenn STD_FAK nicht auf all eingestellt ist?
Nee, das ist natürlich nicht so gewollt und mir auch nicht aufgefallen. Das behebe ich natürlich noch.

> Das in der JSON wird so im Embed angezeigt:
Uff, wie konnte ich das übersehen? Hab beim "aufräumen" nur an die Umlaute gedacht...

2022-03-04 13:40 UTC, dnns01 commented
> > Mit dem Embed kann es dazu führen, dass bei "zu vielen" neuen Stellenangeboten die maximale Größe gesprengt wird.
> 
> Das habe ich nicht bedacht. Sicher haben wir irgendwo bei Boty für diesen Fall schon ein gut funktionierendes Workaround was ich mir abschauen könnte? Hast du spontan ne Idee in welchem der cogs ich da fündig werde?
Help kann auf jeden Fall die Nachricht auf mehrere Embeds aufteilen

2022-03-05 13:22 UTC, samari-k commented
Zwei Probleme habe ich behoben. Mit der Embed-Größe wird es etwas tricky, da ich (soweit ich das überblicke) nicht einfach merere ephemeral-Nachrichten hintereinander senden kann, die sind ja eine response auf eine Interaction. 
Meine Lösung wäre jetzt, dafür vor- und zurück-Buttons zu nutzen. Dann zeige ich immer 5 Stellenanzeigen auf einer "Seite" an und wenn es mehr als fünf gibt, kann man mittels Button die nächsten fünf anzeigen. Ja/nein/vielleicht?

2022-03-05 14:12 UTC, samari-k commented
So sähe das dann aus:
![jobs-pages](https://user-images.githubusercontent.com/74598487/156886965-e8d70e87-3d5a-4103-b8b0-0924137eb997.png)

2022-03-05 14:27 UTC, dnns01 commented
Funktioniert das so schon? Also das umblättern auf die nächste Seite?

2022-03-05 14:53 UTC, samari-k commented
Jetzt ja. Ich gebe es hiermit zum nächsten Review frei :-D

2022-03-19 21:29 UTC, dnns01 commented
@samari-k 
Sieht soweit gut aus. Aber: bei den Stellenangeboten, die automatisch gepostet werden, wird immer noch alles in ein Embed reingesteckt. Vielleicht müssten wir das da noch aufteilen, dass nach 5 Nachrichten einfach ein neues Embed erstellt wird, oder hast du ne andere Idee?

2022-03-29 07:44 UTC, samari-k commented
@dnns01 jetzt wird nach fünf Jobs ein neues Embed angelegt und als neue Nachricht gepostet. was sagst du?

2022-04-04 21:03 UTC, merged