ICS Dateien zum Import in den eigenen Kalender bei Terminen anbieten
FU-Hagen-Discord/fernuni-bot pull request #62
Opened 2021-05-21 20:55 UTC by dnns01

2021-05-23 20:36 UTC, ffaadd requested changes
Die Datei wird erzeugt und zum Download angeboten.
Wenn ich versuche die ICS-Datei über meine (Apple-)Kalender Anwendung zu meinem Google Kalender hinzuzufügen bekomme ich einen Fehler und es wird gefragt ob ich die Lokale- oder die Server-Version behalten möchte. Egal was ich anklicke, der Termin wird nicht eingetragen. Beim icloud Kalender kommt keine Fehlermeldung, der Termin wird aber nicht eingetragen. 
In der Kalenderanwendung wird der Termin angezeigt. Aber nicht als eingetragener Termin sondern in der Seitenleiste
Ich habe beim Erzeugen als `recurring 7d` und als `reminder 10` angegeben. Aus `7d` wurde anstatt 10.080 Minuten 10.080 Tage (siehe Screenshot). Der Hinweis ist auf 15 Minuten (Kalenderstandard) eingestellt. Der Termin hat keinen Zeitraum 22:30-22:30.
Gegentest mit ICS der Entsorgungsbetriebe: Die Kalenderanwendung fragt, ob ein neues Ereignis zum (auswählbaren) Kalender hinzugefügt werden soll. Nach Bestätitgung werden die  Termine eingetragen. 

Mittlerweile ist der Termin verstrichen. Eine Benachrichtigung über den Kalender ist nicht erfolgt.

[das_ist_ein_test_mit_leerzeichen.ics (als txt weil sonst nicht supported)](https://github.com/FU-Hagen-Discord/fernuni-bot/files/6528882/das_ist_ein_test_mit_leerzeichen.txt)

Screenshot aus der Kalenderanwendung:
<img width="380" alt="Bildschirmfoto 2021-05-23 um 22 23 53" src="https://user-images.githubusercontent.com/75286597/119275463-91b7a980-bc15-11eb-9afc-aa37d7cf6813.png">

2021-05-24 09:58 UTC, dnns01 commented
Muss der Apple Kalender sein^^ Wenn ich diese ics in meinen Thunderbird Kalender eintrage, dann funktioniert das wunderbar. Argh.....

2021-05-24 11:45 UTC, ffaadd commented
[funktioniert.ics (als txt)](https://github.com/FU-Hagen-Discord/fernuni-bot/files/6532075/funktioniert.txt)
Hier ein Beispiel was bei mir funktioniert. Evtl. erkennst du ja unterschiede.

2021-07-11 12:01 UTC, ffaadd approved these changes
Kalenderdatei funktionert jetzt im Apple-Kalender mit und ohne reccuring korrekt.

2021-07-11 12:10 UTC, merged