Update learninggroups.py
FU-Hagen-Discord/fernuni-bot pull request #72
Opened 2021-06-04 10:28 UTC by L-MzK

2021-06-10 20:11 UTC, dnns01 requested changes

2021-06-10 20:11 UTC, dnns01 commented on cogs/help.py
> +        if utils.is_mod:
@ffaadd korrigiere mich, wenn ich hier falsch liege, aber ich glaube das würde dafür sorgen, dass einem Mod immer `!mod-hlep` vorgeschlagen wird, egal ob das betreffende Command ein Mod-Command ist, oder nicht.

2021-06-12 10:57 UTC, L-MzK commented on cogs/help.py
> +        if utils.is_mod:
Genau, davon gehe ich aus (habe es aber nicht getestet).
Ich wusste nicht wie man "if command.mods_only:" syntaktisch umsetzen würde.

2021-07-10 20:35 UTC, dnns01 commented
Wegen Umbau des Hilfesystems demnächst irrelevant

2021-07-10 20:35 UTC, closed without merging